identifier: md60lal679zewbg9
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: webPortfolio
homeFolder: /Users/elizabethoconnor/WebstormProjects/webPortfolio
distFolder:
  base: dist/web-portfolio
outDir: /Users/elizabethoconnor/WebstormProjects/webPortfolio/dist/static
handle404: ''
