name: Build, Test, and Prettify
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:


jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run Prettier check
      - name: Run Prettier
        run: npm run format:check
        continue-on-error: false # Fail if Prettier requirements are not met

      # Step 5: Run Jest tests
      - name: Run Jest tests with coverage
        run: npm test -- --coverage

      # Step 6: Build the Angular app
      - name: Build Angular app
        run: npm run build

  enforce-merge:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR can be merged
        run: echo "Ensure all checks have passed before merging to main."
